name: 'Build'

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Publish CurseForge
        run: ./gradlew :Forge:publishCurseForge :Fabric:publishCurseForge :NeoForge:publishCurseForge
      - name: Publish Modrinth
        run: ./gradlew :Forge:modrinth :Fabric:modrinth :NeoForge:modrinth
      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: output/*[^shadow].jar
